name: Tests

permissions:
  contents: read

on:
  push:
    branches:
    - main
    paths-ignore:
    - 'docs/arch/**'
  pull_request:
    paths-ignore:
    - 'docs/arch/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check: [style]
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: pip cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        pip install -U black
    - name: Run check
      run: |
        black --check .

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 40
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: pip cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        set -x
        pip install -U pip setuptools wheel
        pip install -e .[dev]
    - name: Test
      run: |
        set -x
        python -m unittest discover -v

  test-plugins:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 100
      matrix:
        plugin:
        - .
        - configloader/yaml
        - configloader/image
        - model/scratch
        - model/scikit
        - model/tensorflow
        - model/tensorflow_hub
        - model/vowpalWabbit
        - model/xgboost
        - model/pytorch
        - model/spacy
        - model/daal4py
        - model/autosklearn
        - operations/binsec
        - operations/deploy
        - operations/image
        - operations/nlp
        - feature/git
        - feature/auth
        - service/http
        - source/mysql
        - entities/alice
        - examples/shouldi
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Remove unused software
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: pip cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        set -x
        pip install -U pip setuptools wheel
        pip install -e .[dev]
        if [ -f "${{ matrix.plugin }}/setup.py" ]; then
          pip install -e "${{ matrix.plugin }}"
        fi
    - name: Test
      run: |
        set -x
        export LOGGING=debug
        if [ "${{ matrix.plugin }}" = "." ]; then
          python -m unittest discover -v
        else
          cd "${{ matrix.plugin }}"
          python -m unittest discover -v
        fi
